#include <iostream> 
#include <mpi2/mpi2.h> 
#include <mf/register/register-generated.h>

namespace mf { namespace detail { 
void registerGeneratedMatrixTasks() {
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGkl, mf::RegularizeGkl> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGklAbs, mf::RegularizeGklAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGklTruncate, mf::RegularizeGkl> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGklTruncate, mf::RegularizeGklTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGklAbsTruncate, mf::RegularizeGklAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateGklAbsTruncate, mf::RegularizeGklAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGkl, mf::RegularizeGkl, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGklAbs, mf::RegularizeGklAbs, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGklTruncate, mf::RegularizeGkl, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGklTruncate, mf::RegularizeGklTruncate, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGklAbsTruncate, mf::RegularizeGklAbs, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateGklAbsTruncate, mf::RegularizeGklAbsTruncate, mf::GklLoss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSl, mf::RegularizeSl> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSlAbs, mf::RegularizeSlAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSlTruncate, mf::RegularizeSl> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSlTruncate, mf::RegularizeSlTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSlAbsTruncate, mf::RegularizeSlAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateSlAbsTruncate, mf::RegularizeSlAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSl, mf::RegularizeSl, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSlAbs, mf::RegularizeSlAbs, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSlTruncate, mf::RegularizeSl, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSlTruncate, mf::RegularizeSlTruncate, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSlAbsTruncate, mf::RegularizeSlAbs, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateSlAbsTruncate, mf::RegularizeSlAbsTruncate, mf::SlLoss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzsl, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbs, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeNoneTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNoneAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzsl, mf::RegularizeNone, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbs, mf::RegularizeNoneAbs, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeNone, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeNoneTruncate, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNoneAbs, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNoneAbsTruncate, mf::NzslLoss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzsl, mf::RegularizeL1> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbs, mf::RegularizeL1Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeL1> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeL1Truncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL1Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL1AbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzsl, mf::RegularizeL1, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbs, mf::RegularizeL1Abs, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeL1, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeL1Truncate, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL1Abs, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL1AbsTruncate, mf::SumLoss_NzslLoss_L1Loss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzsl, mf::RegularizeL2> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbs, mf::RegularizeL2Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeL2> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeL2Truncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL2Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL2AbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzsl, mf::RegularizeL2, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbs, mf::RegularizeL2Abs, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeL2, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeL2Truncate, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL2Abs, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeL2AbsTruncate, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzsl, mf::RegularizeNzl2> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbs, mf::RegularizeNzl2Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeNzl2> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslTruncate, mf::RegularizeNzl2Truncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNzl2Abs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNzl2AbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzsl, mf::RegularizeNzl2, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbs, mf::RegularizeNzl2Abs, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeNzl2, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslTruncate, mf::RegularizeNzl2Truncate, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNzl2Abs, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslAbsTruncate, mf::RegularizeNzl2AbsTruncate, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2Abs, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2Truncate, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2Truncate, mf::RegularizeNoneTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2AbsTruncate, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslL2AbsTruncate, mf::RegularizeNoneAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2, mf::RegularizeNone, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2Abs, mf::RegularizeNoneAbs, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2Truncate, mf::RegularizeNone, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2Truncate, mf::RegularizeNoneTruncate, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2AbsTruncate, mf::RegularizeNoneAbs, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslL2AbsTruncate, mf::RegularizeNoneAbsTruncate, mf::SumLoss_NzslLoss_L2Loss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2Abs, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2Truncate, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2Truncate, mf::RegularizeNoneTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2AbsTruncate, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateNzslNzl2AbsTruncate, mf::RegularizeNoneAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2, mf::RegularizeNone, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2Abs, mf::RegularizeNoneAbs, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2Truncate, mf::RegularizeNone, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2Truncate, mf::RegularizeNoneTruncate, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2AbsTruncate, mf::RegularizeNoneAbs, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateNzslNzl2AbsTruncate, mf::RegularizeNoneAbsTruncate, mf::SumLoss_NzslLoss_Nzl2Loss> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2Abs, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2Truncate, mf::RegularizeNone> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2Truncate, mf::RegularizeNoneTruncate> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2AbsTruncate, mf::RegularizeNoneAbs> >();
    mpi2::registerTask<mf::detail::DsgdTask<mf::UpdateBiasedNzslNzl2AbsTruncate, mf::RegularizeNoneAbsTruncate> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2, mf::RegularizeNone, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2Abs, mf::RegularizeNoneAbs, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2Truncate, mf::RegularizeNone, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2Truncate, mf::RegularizeNoneTruncate, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2AbsTruncate, mf::RegularizeNoneAbs, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
    mpi2::registerTask<mf::detail::DistributedDecayAutoTask<mf::UpdateBiasedNzslNzl2AbsTruncate, mf::RegularizeNoneAbsTruncate, mf::SumLoss_BiasedNzslLoss_BiasedNzl2Loss> >();
}
} }

